spring:
  application:
    name: video-processing

aws:
  s3:
    bucket-name: soat-storage
  credentials:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
    region: sa-east-1
  sqs:
    endpoint: "https://sqs.sa-east-1.amazonaws.com/588738607552/soat_new_update_file"
    endpoint-notifier: "https://sqs.sa-east-1.amazonaws.com/588738607552/soat_notifier"



cloud:
  aws:
    credentials:
      access-key: ${aws.credentials.access-key}
      secret-key: ${aws.credentials.secret-key}
    region:
      static: ${aws.credentials.region}



server:
  port: 8080

