name: CD - Release
on: 
  pull_request:
    types: [closed]
    branches:
      - main
env:
  REGION_DEFAULT: "us-east-1"
  CLUSTER_NAME: "tech-Challenge"

jobs:     
   deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: AWS Configure
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ID }}
          aws-region: ${{ env.REGION_DEFAULT }}

      - name: Update Kube Config
        run: aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }} --region ${{ env.REGION_DEFAULT }}

      - name: Kube Apply App
        run: kubectl apply  infra/deployment-process-video.yaml
   
      
   